### Get HMS sales file

In [37]:
# Get latest sales data from HMS
!rm -f "kaupskra.csv"
!wget "https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/frs3o1zldvgn/b/public_data_for_download/o/kaupskra.csv"

--2023-04-18 22:24:25--  https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/frs3o1zldvgn/b/public_data_for_download/o/kaupskra.csv
Resolving objectstorage.eu-frankfurt-1.oraclecloud.com (objectstorage.eu-frankfurt-1.oraclecloud.com)... 134.70.40.1, 134.70.44.1, 134.70.48.1
Connecting to objectstorage.eu-frankfurt-1.oraclecloud.com (objectstorage.eu-frankfurt-1.oraclecloud.com)|134.70.40.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36729265 (35M) [text/csv]
Saving to: ‘kaupskra.csv’

kaupskra.csv        100%[===================>]  35,03M  2,86MB/s    in 25s

2023-04-18 22:24:51 (1,40 MB/s) - ‘kaupskra.csv’ saved [36729265/36729265]

In [38]:
import pandas as pd
import numpy as np
kaupskra = pd.read_csv('kaupskra.csv', encoding='ISO-8859-1', sep=',')
kaupskra['postnr'] = kaupskra['postnr'].values.astype(np.int64)
kaupskra

/tmp/ipykernel_14359/3862392147.py:3: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  kaupskra = pd.read_csv('kaupskra.csv', encoding='ISO-8859-1', sep=',')

,faerslunumer,emnr,skjalanumer,fastnum,heimilisfang,postnr,heinum,svfn,sveitarfelag,utgdag,...,kaupverd,fasteignamat,byggar,fepilog,einflm,lod_flm,lod_flmein,tegund,fullbuid,onothaefur_samningur
0,569113,437,S-003590/2012,2064400,Nýbýlavegur 12,200,1022800,1000,Kópavogsbær,2012-07-30 00:00:00.000,...,87000,70850,1985,010101,780.4,1105.0,m²,Atvinnuhúsnæði,1,0
1,558760,436,X-000916/2011,2074439,Drangahraun 10,220,1118718,1400,Hafnarfjarðarkaupstaður,2011-02-28 00:00:00.000,...,36000,40790,1983,010102,400.0,3000.0,m²,Atvinnuhúsnæði,1,0
2,566833,411,S-003191/2012,2264635,Dugguvogur 49,104,1003941,0,Reykjavíkurborg,2012-04-16 00:00:00.000,...,31000,4679,1962,010301,310.2,565.0,m²,Atvinnuhúsnæði,1,1
3,566833,411,S-003191/2012,2264636,Dugguvogur 49,104,1003941,0,Reykjavíkurborg,2012-04-16 00:00:00.000,...,31000,5516,1962,010302,310.2,565.0,m²,Atvinnuhúsnæði,1,1
4,628860,441,E-002286/2018,2264633,Dugguvogur 49,104,1003941,0,Reykjavíkurborg,2018-02-20 00:00:00.000,...,23500,13200,1962,010201,71.4,565.0,m²,Atvinnuhúsnæði,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175997,593730,445,A-002449/2015,2352212,Hamratún 10,600,1140629,6000,Akureyrarbær,2015-05-13 00:00:00.000,...,28700,10900,2015,20201,97.4,3625.2,m²,Fjölbýli,1,0
175998,695843,445,A-007647/2022,2352212,Hamratún 10,600,1140629,6000,Akureyrarbær,2022-12-23 00:00:00.000,...,56700,39500,2015,20201,97.4,3625.2,m²,Fjölbýli,1,0
175999,639254,445,A-008232/2018,2352212,Hamratún 10,600,1140629,6000,Akureyrarbær,2018-12-10 00:00:00.000,...,40800,31550,2015,20201,97.4,3625.2,m²,Fjölbýli,1,0
176000,595753,445,A-004098/2015,2352211,Hamratún 10,600,1140629,6000,Akureyrarbær,2015-07-16 00:00:00.000,...,28200,24500,2015,20102,97.4,3625.2,m²,Fjölbýli,1,0
176001,593899,445,A-002705/2015,2352210,Hamratún 10,600,1140629,6000,Akureyrarbær,2015-05-27 00:00:00.000,...,28200,10900,2015,20101,97.4,3625.2,m²,Fjölbýli,1,0

### Get properties from Vísir

In [39]:
import requests
from random import sample

empty_arr = []

for i in range(1, 6):
    r = requests.get('http://fasteignir.visir.is/api/search?onpage=1000&page='+str(i))
    if r is not None:
        empty_arr.append(r.json())


# Initialize an empty array
arr = []
for inner_array in empty_arr:
    for dictionary in inner_array:
        arr.append(dictionary)

In [40]:
# Look lets look at one sample to see how the data looks like
print(arr[0].keys()) #primary keys but not the nested keys
sample(arr, 1)

dict_keys(['id', 'bedrooms', 'bathrooms', 'street_name', 'street_number', 'sale_or_rent', 'zip', 'price', 'size', 'category', 'rooms', 'images_nr', 'image', 'latitude', 'longitude', 'legit_realestate_agent', 'openhouse'])

[{'id': '469281',
  'bedrooms': '2',
  'bathrooms': '1',
  'street_name': 'Sunnusmári 5 - 103',
  'street_number': '',
  'sale_or_rent': '1',
  'zip': {'zip': '201', 'town': 'Kópavogur'},
  'price': '81900000',
  'size': '101,4',
  'category': 'Fjölbýlishús',
  'rooms': '3',
  'images_nr': '27',
  'image': 'http://api-beta.fasteignir.is/pictures/469281/01d0f2b654411c0bb975f3f776b03021-469x310.jpg',
  'latitude': None,
  'longitude': None,
  'legit_realestate_agent': 'Heimir Hallgrímsson',
  'openhouse': {'property': None,
   'date': None,
   'time_start': None,
   'time_end': None,
   'description': None}}]

In [71]:
kaupskra.sample(2)

,faerslunumer,emnr,skjalanumer,fastnum,heimilisfang,postnr,heinum,svfn,sveitarfelag,utgdag,...,kaupverd,fasteignamat,byggar,fepilog,einflm,lod_flm,lod_flmein,tegund,fullbuid,onothaefur_samningur
22910,535634,411,T-008928/2007,2008110,Bergþórugata 11,101,1002330,0,Reykjavíkurborg,2007-07-11 00:00:00.000,...,9000,9380,1921,010101,39.3,312.7,m²,Fjölbýli,1,0
154645,654699,441,B-003234/2020,2504097,Bæjarlind 5,201,1141313,1000,Kópavogsbær,2020-03-20 00:00:00.000,...,71900,53650,2019,010801,116.7,2971.0,m²,Fjölbýli,1,0

In [85]:
kaupskra["utgdag"]

0         2012-07-30 00:00:00.000
1         2011-02-28 00:00:00.000
2         2012-04-16 00:00:00.000
3         2012-04-16 00:00:00.000
4         2018-02-20 00:00:00.000
                   ...
175997    2015-05-13 00:00:00.000
175998    2022-12-23 00:00:00.000
175999    2018-12-10 00:00:00.000
176000    2015-07-16 00:00:00.000
176001    2015-05-27 00:00:00.000
Name: utgdag, Length: 176002, dtype: object

### Working with the data

In [125]:
from datetime import datetime
def check_if_property_has_been_sold_before(address, zip_number, size):
    previosly_sold_for = []
    if (kaupskra['heimilisfang'].apply(str.lower).eq(address.lower())).any():
        this_address = kaupskra[kaupskra['heimilisfang'].apply(str.lower) == address.lower()]
        
        this_address_and_zip = this_address[this_address["postnr"]==int(zip_number)]
        if this_address_and_zip.shape[0] > 0: # check if correct property based on the zip for property
            with_this_size = this_address_and_zip[this_address_and_zip["einflm"]==size]
            if with_this_size.shape[0] > 0: # check if same fm
                # df_to_use = with_this_size.copy()
                # df_to_use['utgdag'] = pd.to_datetime(df_to_use['utgdag'])
                # df_to_use = df_to_use.sort_values(by='utgdag', inplace = True) 
                
                previosly_sold_for = with_this_size["kaupverd"].div(1000).round(2).to_numpy()
                utgafu_dagur = with_this_size["utgdag"].to_numpy()
                for p in range(0, len(previosly_sold_for)):
                    sold_date = datetime.strptime(utgafu_dagur[p], '%Y-%m-%d %H:%M:%S.%f').strftime('%d %B %Y')
                    print("Previous price: "+ str(previosly_sold_for[p]) + " milljonir ("+ sold_date + ")")
        
def print_out_details(items):
    for item in items:
        print(item)

In [126]:
show_top_n = 25
for item in arr[0:show_top_n]:
    # values from columns inside the printable string (if applies)
    address = item["street_name"] + " " +  item["street_number"]
    size = float(item["size"].replace(",", "."))
    zip = item["zip"]["zip"]
    price_in_millions_isk = int(item["price"])/1000000

    # Texts
    TEXT_for_sale_or_rent = "Til sölu" if item["sale_or_rent"] == '1' else "Til leigu"
    TEXT_size = "Fermeterar: " + str(size)
    TEXT_price = f"Verð: {str(price_in_millions_isk)} milljónir" if float(price_in_millions_isk) != 0.0 else f"Verð: Tilboð"
    print_out_details(items=[address, TEXT_for_sale_or_rent, TEXT_size,TEXT_price])
    
    # check kaupskra.csv for if this property has been sold previously
    check_if_property_has_been_sold_before(address=address, zip_number=zip, size=size)
    print("\n")

Naustavör 58
Til sölu
Fermeterar: 129.0
Verð: 132.0 milljónir


Naustavör 58
Til sölu
Fermeterar: 101.3
Verð: 98.0 milljónir


Naustavör 58
Til sölu
Fermeterar: 128.2
Verð: 133.0 milljónir


Naustavör 58
Til sölu
Fermeterar: 101.4
Verð: 98.0 milljónir


Síðumúli 39
Til sölu
Fermeterar: 79.8
Verð: 68.9 milljónir
Previous price: 49.5 milljonir (07 January 2021)


Maríugata 1 ib 502
Til sölu
Fermeterar: 81.7
Verð: 79.9 milljónir


Maríugata 1 ib 503
Til sölu
Fermeterar: 98.6
Verð: 91.9 milljónir


Maríugata 1 ib 405
Til sölu
Fermeterar: 81.3
Verð: 72.9 milljónir


Kjarnagata 65 íbúð 103
Til sölu
Fermeterar: 87.8
Verð: 59.99 milljónir


Kjarnagata 65 íbúð 101
Til sölu
Fermeterar: 87.5
Verð: 59.99 milljónir


Hulduholt 10 - Nýbygging
Til sölu
Fermeterar: 118.2
Verð: 76.9 milljónir


Hulduholt 8 - Nýbygging
Til sölu
Fermeterar: 118.2
Verð: 76.9 milljónir


Funalind 11
Til sölu
Fermeterar: 110.1
Verð: 79.5 milljónir
Previous price: 69.9 milljonir (24 November 2022)
Previous price: 28.9 milljonir (30 January 2014)
Previous price: 27.4 milljonir (08 February 2007)


Hamrabyggð 14
Til sölu
Fermeterar: 193.7
Verð: 124.9 milljónir
Previous price: 46.5 milljonir (06 June 2007)
Previous price: 48.0 milljonir (11 June 2014)
Previous price: 67.5 milljonir (03 April 2018)


Garðaflöt 16
Til sölu
Fermeterar: 235.6
Verð: 240.0 milljónir
Previous price: 19.8 milljonir (27 November 2012)


Mýrarkot 6
Til sölu
Fermeterar: 200.9
Verð: 119.8 milljónir


Arnarhraun 20
Til sölu
Fermeterar: 86.4
Verð: 60.9 milljónir
Previous price: 17.1 milljonir (15 April 2011)
Previous price: 18.3 milljonir (20 September 2007)
Previous price: 37.5 milljonir (24 September 2019)
Previous price: 17.82 milljonir (09 February 2012)


Bakkatún 6
Til sölu
Fermeterar: 155.1
Verð: 86.9 milljónir
Previous price: 36.5 milljonir (20 September 2016)
Previous price: 57.9 milljonir (26 September 2019)


Bakkastaðir 61
Til sölu
Fermeterar: 180.7
Verð: 114.9 milljónir
Previous price: 75.1 milljonir (05 December 2018)


Suðurgata 68
Til sölu
Fermeterar: 67.2
Verð: 49.9 milljónir
Previous price: 40.5 milljonir (02 December 2021)
Previous price: 35.5 milljonir (18 December 2020)
Previous price: 12.85 milljonir (11 October 2013)


Hlíðarvegur 22
Til sölu
Fermeterar: 168.8
Verð: 34.9 milljónir


Strandgata 2
Til sölu
Fermeterar: 357.8
Verð: Tilboð
Previous price: 18.8 milljonir (23 January 2009)
Previous price: 7.0 milljonir (18 December 2019)


Aðalgata 2
Til sölu
Fermeterar: 294.1
Verð: 75.0 milljónir


Reynimelur 72
Til sölu
Fermeterar: 74.3
Verð: 59.5 milljónir
Previous price: 18.5 milljonir (01 March 2007)
Previous price: 42.5 milljonir (19 November 2020)
Previous price: 38.7 milljonir (09 August 2018)


Arnarhlíð 4 ib. 210
Til sölu
Fermeterar: 125.7
Verð: 109.9 milljónir

In [122]:
kaupskra["utgdag"]

0         2012-07-30 00:00:00.000
1         2011-02-28 00:00:00.000
2         2012-04-16 00:00:00.000
3         2012-04-16 00:00:00.000
4         2018-02-20 00:00:00.000
                   ...
175997    2015-05-13 00:00:00.000
175998    2022-12-23 00:00:00.000
175999    2018-12-10 00:00:00.000
176000    2015-07-16 00:00:00.000
176001    2015-05-27 00:00:00.000
Name: utgdag, Length: 176002, dtype: object

In [81]:
check_if_property_has_been_sold_before(address="Suðurgata 83", zip_number=220, size=78.6)

Previous price: 15.4 milljonir
Previous price: 38.0 milljonir